name: build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: Compile SCSS
        run: |
          sudo apt-get install -y sassc
          bash tools/compile-scss-sassc.sh

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: gyarb-dist
          path: .
