name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: cirrus

      - name: Do the things
        run: |
          cd cirrus
          ./tools/make-dist.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: cirrus-dist
          path: ./cirrus-dist.zip

      - name: Upload and tag
        uses: pyTooling/Actions/releaser@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'latest'
          files: ./cirrus-dist.zip
        if: github.event_name != 'pull_request'
